#!/usr/bin/env node

// Single command to try out the Gadgets Workshop locally:
//
//   1. Installs dependencies (if needed).
//   2. Builds only what's required to *run* the app:
//        - @gadgets/typed-storage  (the backend imports it via its built `dist` output)
//        - the frontend bundle     (`vite build` -> packages/workshop-frontend/dist)
//      Gatekeeper configurator files are generated by run-dev-server.ts at startup.
//   3. Launches the local server (run-dev-server.ts --serve-frontend-assets), which serves the
//      built frontend as static assets on the backend.
//
// Vite+ owns the build cache and restores missing outputs on warm runs.

import { execFileSync, spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDevServerConfig } from "./dev-server-config.ts";
import { pnpmCommand } from "./pnpm-command.ts";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// Forward any extra flags (e.g. --use-workers-ai-binding) on to run-dev-server.ts.
const passthroughArgs = process.argv.slice(2);
let backendHost: string;
try {
  ({ backendHost } = getDevServerConfig(passthroughArgs, process.env.VITE_BACKEND_HOST));
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}


function runPnpm(args: string[]): void {
  console.log(`\n> pnpm ${args.join(" ")}`);
  const [command, argv] = pnpmCommand(args);
  execFileSync(command, argv, { stdio: "inherit", cwd: ROOT });
}

runPnpm(["install"]);
runPnpm(["exec", "vp", "run", "--cache", "@gadgets/typed-storage#build"]);
runPnpm(["exec", "vp", "run", "--cache", "@gadgets/workshop-frontend#build:assets"]);

// ---------------------------------------------------------------------------
// Launch the local server (serves the built frontend as static assets).
// ---------------------------------------------------------------------------

console.log(`\nStarting local server at http://${backendHost} ...`);
const server = spawn(
    process.execPath,
    [join(ROOT, "scripts", "run-dev-server.ts"), "--serve-frontend-assets", ...passthroughArgs],
    { stdio: "inherit", cwd: ROOT });

server.on("exit", (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  else process.exit(code ?? 0);
});
